/* This file was autogenerated via
 ----------------------------------------
 ldetool generate --package main Line.lde
 ----------------------------------------
do not touch it with bare hands!
*/

package main

import (
	"bytes"
)

// Line autogenerated parser
type Line struct {
	rest []byte
	Time []byte
}

// Extract autogenerated method of Line
func (p *Line) Extract(line []byte) (bool, error) {
	var pos int
	p.rest = line

	// Checks if the rest starts with '[' symbol and pass it
	if len(p.rest) > 0 && p.rest[0] == '[' {
		p.rest = p.rest[1:]
	} else {
		return false, nil
	}

	// Put data before ']' into Time
	if pos = bytes.IndexByte(p.rest, ']'); pos >= 0 {
		p.Time = p.rest[:pos]

		p.rest = p.rest[pos+1:]
	} else {
		return false, nil
	}

	return true, nil
}
